apiVersion: v1
kind: Service
metadata:
  name: vcas-demo-svc
  namespace: default
spec:
  selector:
    app: vcas-demo-app
  ports:
  - protocol: TCP
    port: 80
    targetPort: 8080
  type: LoadBalancer
